### ISSUE TITLE
No implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by slemrmartin** [zshannon/cloudwatchlogger#16]
With the release 0.3.0, our apps started crashing there (looks like it's related to #12)

```
#<CloudWatchLogger::Client::AWS_SDK::DeliveryThread:0x000055d9d76eadf0@/usr/share/gems/gems/cloudwatchlogger-0.3.0/lib/cloudwatchlogger/client/aws_sdk/threaded.rb:49 run> terminated with exception (report_on_exception is true):
--
  | /usr/share/gems/gems/cloudwatchlogger-0.3.0/lib/cloudwatchlogger/client/aws_sdk/threaded.rb:61:in `[]': no implicit conversion of Symbol into Integer (TypeError)
  | from /usr/share/gems/gems/cloudwatchlogger-0.3.0/lib/cloudwatchlogger/client/aws_sdk/threaded.rb:61:in `block (2 levels) in initialize'
  | from /usr/share/gems/gems/cloudwatchlogger-0.3.0/lib/cloudwatchlogger/client/aws_sdk/threaded.rb:50:in `loop'
  | from /usr/share/gems/gems/cloudwatchlogger-0.3.0/lib/cloudwatchlogger/client/aws_sdk/threaded.rb:50:in `block in initialize'
```

Is it something new we have to set somewhere or is it a bug?

cc @coderbydesign @zshannon

**Comment by slemrmartin** [comment]
So the problem is following:

It's expecting the logger will use only the default `client.formatter` method (it's converting message to hash)

we're using `ManageIQ::Loggers`, which is using `ManageIQ::Loggers::Container::Formatter`
https://github.com/ManageIQ/manageiq-loggers/blob/master/lib/manageiq/loggers/cloud_watch.rb#L27
